### ISSUE TITLE
Start-Up CTD

### ISSUE THREAD

**Issue by ZuluGriselda** [ArranzCNL/ImprovedCameraSE#4]
I got CTD when starting up my game, I was also installing DynDOLOD at that moment, and I can confirm it is not the one that caused the CTDs. Here's my Load Order:
[Zulu's Load Order.txt](https://github.com/ArranzCNL/ImprovedCameraSE/files/8935597/Zulu.s.Load.Order.txt)

**Comment by ZuluGriselda** [comment]
I got CTD when starting up my game, I was also installing DynDOLOD at that moment, and I can confirm it is not the one that caused the CTDs. Here's my Load Order:

[Zulu's Load Order.txt](https://github.com/ArranzCNL/ImprovedCameraSE/files/8935594/Zulu.s.Load.Order.txt)

**Comment by ArranzCNL** [comment]
Improved Camera can be quite intensive on startup, in your normal log directory:
Documents/My Games/Skyrim Special Edition/SKSE/

Can you post:
ImprovedCameraSE.log

Also which other SKSE mods do you use?

A crash can just randomly occur when we hook D3D11 or DirectInput not sure why it fails, happens extremely rare. (I've had it happen 3 times in a month but that is loading the game over 1000+ times)

**Comment by AdeltonA** [comment]
I am getting CTD when I start up the game.
[ImprovedCameraSE.log](https://github.com/ArranzCNL/ImprovedCameraSE/files/8935690/ImprovedCameraSE.log)

**Comment by ArranzCNL** [comment]
Are you getting a Msgbox or anything popup or just instantly closing the game.

Also still need to know which skse mods you are using.

**Comment by TwistedModding** [comment]
https://www.nexusmods.com/skyrimspecialedition/mods/21294 If possible, can you use this mod to gather a crash log and post it? Would be helpful in finding out the issue

But to narrow down possible causes, this can also be from an outdated patch, using a skse plugin not meant for your version of skyrim, anti virus messing with mo2s VFS.

**Comment by AdeltonA** [comment]
I am getting the crash before reaching the menu so there won't be any .NET logs.

**Comment by dicecd00** [comment]
I believe it's because you're using smoothcam, my game crashed on startup when I had smoothcam enabled, and didn't crash when it was disabled.

**Comment by ArranzCNL** [comment]
Are you able to do some testing in regards with that to help isolate the actual issue, I know TwistedModding has SmoothCam installed without issues, might be something specifically enabled with SmoothCam causing it.

Offical SmoothCam support will be coming, current priority is stablizing against base game.

**Comment by dicecd00** [comment]
so I was able to reproduce the crash every time I started the game with smoothcam 1.6.1 and 1.6 with both the esp and esl versions of each, but I ran the game with both 1.5 and 1.0 releases and they worked perfectly, no crash. Any ideas?

**Comment by dicecd00** [comment]
Mod is coming along great btw.

**Comment by ZuluGriselda** [comment]
Here's the log file

[ImprovedCameraSE.log](https://github.com/ArranzCNL/ImprovedCameraSE/files/8948310/ImprovedCameraSE.log)

**Comment by ZuluGriselda** [comment]
> Are you getting a Msgbox or anything popup or just instantly closing the game.
> 
> Also still need to know which skse mods you are using.

I don't even get to see the menu, it just straight up sent me back to Desktop
how do I make a list about SKSEs mod?

**Comment by ZuluGriselda** [comment]
> I believe it's because you're using SmoothCam, my game crashed on startup when I had SmoothCam enabled, and didn't crash when it was disabled.

Oh yes, I tried turning off SmoothCam and it worked
but I saw some bug, I think the magic casting is offside and probably broken

Here's what I mean:
https://www.mediafire.com/file/42k91lq2a9ww12m/Skyrim+Special+Edition+2022-06-21+18-43-26.mp4/file
((sorry if the file were too big))

**Comment by ArranzCNL** [comment]
Magic casting is a different issue and been reported, it is fixed in upcoming PR 2.

> so I was able to reproduce the crash every time I started the game with smoothcam 1.6.1 and 1.6 with both the esp and esl versions of each, but I ran the game with both 1.5 and 1.0 releases and they worked perfectly, no crash. Any ideas?

The changes I see from SmoothCam are upgrading to CommonLibSSE, without fully looking at its source code I cannot tell.
If 1.5 is working with the current PR that is something at least, until we get around to looking fully into various mods and their incompatibilities.

I shall close this now as the issue has been found and due to conflict with SmoothCam 1.6+

**Comment by TwistedModding** [comment]
I'd just like to note I am currently using smoothcam version 1.6.1, and i am not having any crashes with improved camera. I also have a number of people I've asked on the latest version of smoothcam, and the game is still not crashing on startup. I suspect something else is still going on.
